//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkshayPopulationServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://akshay.com/populationservices", ConfigurationName="AkshayPopulationServiceReference.PopulationLiveSoap")]
    public interface PopulationLiveSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://akshay.com/populationservices/GetTotalPopulation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetTotalPopulationResponse> GetTotalPopulationAsync(AkshayPopulationServiceReference.GetTotalPopulationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://akshay.com/populationservices/GetPopulationInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetPopulationInfoResponse> GetPopulationInfoAsync(AkshayPopulationServiceReference.GetPopulationInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://akshay.com/populationservices")]
    public partial class UserAuthSoapHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://akshay.com/populationservices")]
    public partial class PopulationInfo
    {
        
        private int malesField;
        
        private int femalesField;
        
        private int othersField;
        
        private int below18Field;
        
        private int above65Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Males
        {
            get
            {
                return this.malesField;
            }
            set
            {
                this.malesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Females
        {
            get
            {
                return this.femalesField;
            }
            set
            {
                this.femalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Others
        {
            get
            {
                return this.othersField;
            }
            set
            {
                this.othersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Below18
        {
            get
            {
                return this.below18Field;
            }
            set
            {
                this.below18Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Above65
        {
            get
            {
                return this.above65Field;
            }
            set
            {
                this.above65Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTotalPopulation", WrapperNamespace="http://akshay.com/populationservices", IsWrapped=true)]
    public partial class GetTotalPopulationRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://akshay.com/populationservices")]
        public AkshayPopulationServiceReference.UserAuthSoapHeader UserAuthSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://akshay.com/populationservices", Order=0)]
        public string city;
        
        public GetTotalPopulationRequest()
        {
        }
        
        public GetTotalPopulationRequest(AkshayPopulationServiceReference.UserAuthSoapHeader UserAuthSoapHeader, string city)
        {
            this.UserAuthSoapHeader = UserAuthSoapHeader;
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTotalPopulationResponse", WrapperNamespace="http://akshay.com/populationservices", IsWrapped=true)]
    public partial class GetTotalPopulationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://akshay.com/populationservices", Order=0)]
        public int GetTotalPopulationResult;
        
        public GetTotalPopulationResponse()
        {
        }
        
        public GetTotalPopulationResponse(int GetTotalPopulationResult)
        {
            this.GetTotalPopulationResult = GetTotalPopulationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPopulationInfo", WrapperNamespace="http://akshay.com/populationservices", IsWrapped=true)]
    public partial class GetPopulationInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://akshay.com/populationservices")]
        public AkshayPopulationServiceReference.UserAuthSoapHeader UserAuthSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://akshay.com/populationservices", Order=0)]
        public string city;
        
        public GetPopulationInfoRequest()
        {
        }
        
        public GetPopulationInfoRequest(AkshayPopulationServiceReference.UserAuthSoapHeader UserAuthSoapHeader, string city)
        {
            this.UserAuthSoapHeader = UserAuthSoapHeader;
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPopulationInfoResponse", WrapperNamespace="http://akshay.com/populationservices", IsWrapped=true)]
    public partial class GetPopulationInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://akshay.com/populationservices", Order=0)]
        public AkshayPopulationServiceReference.PopulationInfo GetPopulationInfoResult;
        
        public GetPopulationInfoResponse()
        {
        }
        
        public GetPopulationInfoResponse(AkshayPopulationServiceReference.PopulationInfo GetPopulationInfoResult)
        {
            this.GetPopulationInfoResult = GetPopulationInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface PopulationLiveSoapChannel : AkshayPopulationServiceReference.PopulationLiveSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class PopulationLiveSoapClient : System.ServiceModel.ClientBase<AkshayPopulationServiceReference.PopulationLiveSoap>, AkshayPopulationServiceReference.PopulationLiveSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PopulationLiveSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PopulationLiveSoapClient.GetBindingForEndpoint(endpointConfiguration), PopulationLiveSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PopulationLiveSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PopulationLiveSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PopulationLiveSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PopulationLiveSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PopulationLiveSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetTotalPopulationResponse> AkshayPopulationServiceReference.PopulationLiveSoap.GetTotalPopulationAsync(AkshayPopulationServiceReference.GetTotalPopulationRequest request)
        {
            return base.Channel.GetTotalPopulationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetTotalPopulationResponse> GetTotalPopulationAsync(AkshayPopulationServiceReference.UserAuthSoapHeader UserAuthSoapHeader, string city)
        {
            AkshayPopulationServiceReference.GetTotalPopulationRequest inValue = new AkshayPopulationServiceReference.GetTotalPopulationRequest();
            inValue.UserAuthSoapHeader = UserAuthSoapHeader;
            inValue.city = city;
            return ((AkshayPopulationServiceReference.PopulationLiveSoap)(this)).GetTotalPopulationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetPopulationInfoResponse> AkshayPopulationServiceReference.PopulationLiveSoap.GetPopulationInfoAsync(AkshayPopulationServiceReference.GetPopulationInfoRequest request)
        {
            return base.Channel.GetPopulationInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetPopulationInfoResponse> GetPopulationInfoAsync(AkshayPopulationServiceReference.UserAuthSoapHeader UserAuthSoapHeader, string city)
        {
            AkshayPopulationServiceReference.GetPopulationInfoRequest inValue = new AkshayPopulationServiceReference.GetPopulationInfoRequest();
            inValue.UserAuthSoapHeader = UserAuthSoapHeader;
            inValue.city = city;
            return ((AkshayPopulationServiceReference.PopulationLiveSoap)(this)).GetPopulationInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PopulationLiveSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PopulationLiveSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PopulationLiveSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44309/PopulationLive.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PopulationLiveSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44309/PopulationLive.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PopulationLiveSoap,
            
            PopulationLiveSoap12,
        }
    }
}
