//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkshayPopulationServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PopulationInfo", Namespace="http://akshay.com/populationservices")]
    public partial class PopulationInfo : object
    {
        
        private int MalesField;
        
        private int FemalesField;
        
        private int OthersField;
        
        private int Below18Field;
        
        private int Above65Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Males
        {
            get
            {
                return this.MalesField;
            }
            set
            {
                this.MalesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Females
        {
            get
            {
                return this.FemalesField;
            }
            set
            {
                this.FemalesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Others
        {
            get
            {
                return this.OthersField;
            }
            set
            {
                this.OthersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Below18
        {
            get
            {
                return this.Below18Field;
            }
            set
            {
                this.Below18Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Above65
        {
            get
            {
                return this.Above65Field;
            }
            set
            {
                this.Above65Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://akshay.com/populationservices", ConfigurationName="AkshayPopulationServiceReference.PopulationDevSoap")]
    public interface PopulationDevSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://akshay.com/populationservices/GetTotalPopulation", ReplyAction="*")]
        System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetTotalPopulationResponse> GetTotalPopulationAsync(AkshayPopulationServiceReference.GetTotalPopulationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://akshay.com/populationservices/GetPopulationInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetPopulationInfoResponse> GetPopulationInfoAsync(AkshayPopulationServiceReference.GetPopulationInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalPopulationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalPopulation", Namespace="http://akshay.com/populationservices", Order=0)]
        public AkshayPopulationServiceReference.GetTotalPopulationRequestBody Body;
        
        public GetTotalPopulationRequest()
        {
        }
        
        public GetTotalPopulationRequest(AkshayPopulationServiceReference.GetTotalPopulationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://akshay.com/populationservices")]
    public partial class GetTotalPopulationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public GetTotalPopulationRequestBody()
        {
        }
        
        public GetTotalPopulationRequestBody(string city)
        {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalPopulationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalPopulationResponse", Namespace="http://akshay.com/populationservices", Order=0)]
        public AkshayPopulationServiceReference.GetTotalPopulationResponseBody Body;
        
        public GetTotalPopulationResponse()
        {
        }
        
        public GetTotalPopulationResponse(AkshayPopulationServiceReference.GetTotalPopulationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://akshay.com/populationservices")]
    public partial class GetTotalPopulationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTotalPopulationResult;
        
        public GetTotalPopulationResponseBody()
        {
        }
        
        public GetTotalPopulationResponseBody(int GetTotalPopulationResult)
        {
            this.GetTotalPopulationResult = GetTotalPopulationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPopulationInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPopulationInfo", Namespace="http://akshay.com/populationservices", Order=0)]
        public AkshayPopulationServiceReference.GetPopulationInfoRequestBody Body;
        
        public GetPopulationInfoRequest()
        {
        }
        
        public GetPopulationInfoRequest(AkshayPopulationServiceReference.GetPopulationInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://akshay.com/populationservices")]
    public partial class GetPopulationInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public GetPopulationInfoRequestBody()
        {
        }
        
        public GetPopulationInfoRequestBody(string city)
        {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPopulationInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPopulationInfoResponse", Namespace="http://akshay.com/populationservices", Order=0)]
        public AkshayPopulationServiceReference.GetPopulationInfoResponseBody Body;
        
        public GetPopulationInfoResponse()
        {
        }
        
        public GetPopulationInfoResponse(AkshayPopulationServiceReference.GetPopulationInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://akshay.com/populationservices")]
    public partial class GetPopulationInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AkshayPopulationServiceReference.PopulationInfo GetPopulationInfoResult;
        
        public GetPopulationInfoResponseBody()
        {
        }
        
        public GetPopulationInfoResponseBody(AkshayPopulationServiceReference.PopulationInfo GetPopulationInfoResult)
        {
            this.GetPopulationInfoResult = GetPopulationInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface PopulationDevSoapChannel : AkshayPopulationServiceReference.PopulationDevSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class PopulationDevSoapClient : System.ServiceModel.ClientBase<AkshayPopulationServiceReference.PopulationDevSoap>, AkshayPopulationServiceReference.PopulationDevSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PopulationDevSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PopulationDevSoapClient.GetBindingForEndpoint(endpointConfiguration), PopulationDevSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PopulationDevSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PopulationDevSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PopulationDevSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PopulationDevSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PopulationDevSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetTotalPopulationResponse> AkshayPopulationServiceReference.PopulationDevSoap.GetTotalPopulationAsync(AkshayPopulationServiceReference.GetTotalPopulationRequest request)
        {
            return base.Channel.GetTotalPopulationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetTotalPopulationResponse> GetTotalPopulationAsync(string city)
        {
            AkshayPopulationServiceReference.GetTotalPopulationRequest inValue = new AkshayPopulationServiceReference.GetTotalPopulationRequest();
            inValue.Body = new AkshayPopulationServiceReference.GetTotalPopulationRequestBody();
            inValue.Body.city = city;
            return ((AkshayPopulationServiceReference.PopulationDevSoap)(this)).GetTotalPopulationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetPopulationInfoResponse> AkshayPopulationServiceReference.PopulationDevSoap.GetPopulationInfoAsync(AkshayPopulationServiceReference.GetPopulationInfoRequest request)
        {
            return base.Channel.GetPopulationInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AkshayPopulationServiceReference.GetPopulationInfoResponse> GetPopulationInfoAsync(string city)
        {
            AkshayPopulationServiceReference.GetPopulationInfoRequest inValue = new AkshayPopulationServiceReference.GetPopulationInfoRequest();
            inValue.Body = new AkshayPopulationServiceReference.GetPopulationInfoRequestBody();
            inValue.Body.city = city;
            return ((AkshayPopulationServiceReference.PopulationDevSoap)(this)).GetPopulationInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PopulationDevSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PopulationDevSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PopulationDevSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44309/PopulationDev.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PopulationDevSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44309/PopulationDev.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PopulationDevSoap,
            
            PopulationDevSoap12,
        }
    }
}
